version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq/
      - ./.data/rabbitmq:/var/log/rabbitmq
    environment:
      - USER=admin
      - PASSWORD=one_media_2020
